### ISSUE TITLE
Scrolling down does not work on form

### ISSUE THREAD

**Issue by mctraub** [vsaase/covid19selfreport#11]
<img width="1702" alt="Screenshot 2020-03-22 at 13 42 07" src="https://user-images.githubusercontent.com/3026200/77249659-01618b80-6c43-11ea-9f10-de182f3c1740.png">

I cannot scroll down to the questions at the bottom of the form (Firefox 73.0.1 (64-Bit) on MacOs Catalina). 

That also means I cannot click the submit button.

**Comment by vsaase** [comment]
maybe because of main.css :

```

html, body {
    height: 100%;
    margin: 0;
    padding: 0;
    overflow: hidden
}
```

**Comment by vsaase** [comment]
i'll remove the overflow hidden thing

**Comment by vsaase** [comment]
didnt help, something to do with postition:fixed of the report, I am no CSS expert. @firebatgit can you have a look?

**Comment by Skhurana136** [comment]
I think it works now

**Comment by mctraub** [comment]
Yes, works. 👍
